### PR TITLE
Upgrade to Pants 2.12.0

### PR DESCRIPTION
**Pull request by benjyw**

### CODE REVIEW

**Review by Eric-Arellano — APPROVED** [review]
Thanks. Please create a `2.11` branch before merging

**Comment by benjyw** [comment]
There already was a 2.11 branch, and it had diverged. I fixed it up and pushed it directly, to match the state of main before this PR, but with 2.11.0 instead of the rc.

**Review by Eric-Arellano — APPROVED** [review]
Thanks for fixing! Why was it necessary to upgrade protobuf? I didn't realize users would need to make any changes

**Comment by benjyw** [comment]
> Because pants 2.12 apparently upgraded the default protoc, and the new generated code was not compatible with the old runtime

**Pull request merged**
